tinymce.addI18n('hi',{
"Redo": "Redo hi",
"Undo": "Undo hi",
"Cut": "Cut hi",
"Copy": "Copy hi",
"Paste": "Paste hi",
"Select all": "Select all hi",
"New document": "New document hi",
"Ok": "Ok hi",
"Cancel": "Cancel hi",
"Visual aids": "Visual aids hi",
"Bold": "Bold hi",
"Italic": "Italic hi",
"Underline": "Underline hi",
"Strikethrough": "Strikethrough hi",
"Superscript": "Superscript hi",
"Subscript": "Subscript hi",
"Clear formatting": "Clear formatting hi",
"Align left": "Align left hi",
"Align center": "Align center hi",
"Align right": "Align right hi",
"Justify": "Justify hi",
"Bullet list": "Bullet list hi",
"Numbered list": "Numbered list hi",
"Decrease indent": "Decrease indent hi",
"Increase indent": "Increase indent hi",
"Close": "Close hi",
"Formats": "Formats hi",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead. hi",
"Headers": "Headers hi",
"Header 1": "Header 1 hi",
"Header 2": "Header 2 hi",
"Header 3": "Header 3 hi",
"Header 4": "Header 4 hi",
"Header 5": "Header 5 hi",
"Header 6": "Header 6 hi",
"Headings": "Headings hi",
"Heading 1": "Heading 1 hi",
"Heading 2": "Heading 2 hi",
"Heading 3": "Heading 3 hi",
"Heading 4": "Heading 4 hi",
"Heading 5": "Heading 5 hi",
"Heading 6": "Heading 6 hi",
"Preformatted": "Preformatted hi",
"Div": "Div hi",
"Pre": "Pre hi",
"Code": "Code hi",
"Paragraph": "Paragraph hi",
"Blockquote": "Blockquote hi",
"Inline": "Inline hi",
"Blocks": "Blocks hi",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off. hi",
"Font Family": "Font Family hi",
"Font Sizes": "Font Sizes hi",
"Class": "Class hi",
"Browse for an image": "Browse for an image hi",
"OR": "OR hi",
"Drop an image here": "Drop an image here hi",
"Upload": "Upload hi",
"Block": "Block hi",
"Align": "Align hi",
"Default": "Default hi",
"Circle": "Circle hi",
"Disc": "Disc hi",
"Square": "Square hi",
"Lower Alpha": "Lower Alpha hi",
"Lower Greek": "Lower Greek hi",
"Lower Roman": "Lower Roman hi",
"Upper Alpha": "Upper Alpha hi",
"Upper Roman": "Upper Roman hi",
"Anchor": "Anchor hi",
"Name": "Name hi",
"Id": "Id hi",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores. hi",
"You have unsaved changes are you sure you want to navigate away?": "You have unsaved changes are you sure you want to navigate away? hi",
"Restore last draft": "Restore last draft hi",
"Special character": "Special character hi",
"Source code": "Source code hi",
"Insert\/Edit code sample": "Insert\/Edit code sample hi",
"Language": "Language hi",
"Code sample": "Code sample hi",
"Color": "Color hi",
"R": "R hi",
"G": "G hi",
"B": "B hi",
"Left to right": "Left to right hi",
"Right to left": "Right to left hi",
"Emoticons": "Emoticons hi",
"Document properties": "Document properties hi",
"Title": "Title hi",
"Keywords": "Keywords hi",
"Description": "Description hi",
"Robots": "Robots hi",
"Author": "Author hi",
"Encoding": "Encoding hi",
"Fullscreen": "Fullscreen hi",
"Action": "Action hi",
"Shortcut": "Shortcut hi",
"Help": "Help hi",
"Address": "Address hi",
"Focus to menubar": "Focus to menubar hi",
"Focus to toolbar": "Focus to toolbar hi",
"Focus to element path": "Focus to element path hi",
"Focus to contextual toolbar": "Focus to contextual toolbar hi",
"Insert link (if link plugin activated)": "Insert link (if link plugin activated) hi",
"Save (if save plugin activated)": "Save (if save plugin activated) hi",
"Find (if searchreplace plugin activated)": "Find (if searchreplace plugin activated) hi",
"Plugins installed ({0}):": "Plugins installed ({0}): hi",
"Premium plugins:": "Premium plugins: hi",
"Learn more...": "Learn more... hi",
"You are using {0}": "You are using {0} hi",
"Plugins": "Plugins hi",
"Handy Shortcuts": "Handy Shortcuts hi",
"Horizontal line": "Horizontal line hi",
"Insert\/edit image": "Insert\/edit image hi",
"Image description": "Image description hi",
"Source": "Source hi",
"Dimensions": "Dimensions hi",
"Constrain proportions": "Constrain proportions hi",
"General": "General hi",
"Advanced": "Advanced hi",
"Style": "Style hi",
"Vertical space": "Vertical space hi",
"Horizontal space": "Horizontal space hi",
"Border": "Border hi",
"Insert image": "Insert image hi",
"Image": "Image hi",
"Image list": "Image list hi",
"Rotate counterclockwise": "Rotate counterclockwise hi",
"Rotate clockwise": "Rotate clockwise hi",
"Flip vertically": "Flip vertically hi",
"Flip horizontally": "Flip horizontally hi",
"Edit image": "Edit image hi",
"Image options": "Image options hi",
"Zoom in": "Zoom in hi",
"Zoom out": "Zoom out hi",
"Crop": "Crop hi",
"Resize": "Resize hi",
"Orientation": "Orientation hi",
"Brightness": "Brightness hi",
"Sharpen": "Sharpen hi",
"Contrast": "Contrast hi",
"Color levels": "Color levels hi",
"Gamma": "Gamma hi",
"Invert": "Invert hi",
"Apply": "Apply hi",
"Back": "Back hi",
"Insert date\/time": "Insert date\/time hi",
"Date\/time": "Date\/time hi",
"Insert link": "Insert link hi",
"Insert\/edit link": "Insert\/edit link hi",
"Text to display": "Text to display hi",
"Url": "Url hi",
"Target": "Target hi",
"None": "None hi",
"New window": "New window hi",
"Remove link": "Remove link hi",
"Anchors": "Anchors hi",
"Link": "Link hi",
"Paste or type a link": "Paste or type a link hi",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix? hi",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix? hi",
"Link list": "Link list hi",
"Insert video": "Insert video hi",
"Insert\/edit video": "Insert\/edit video hi",
"Insert\/edit media": "Insert\/edit media hi",
"Alternative source": "Alternative source hi",
"Poster": "Poster hi",
"Paste your embed code below:": "Paste your embed code below: hi",
"Embed": "Embed hi",
"Media": "Media hi",
"Nonbreaking space": "Nonbreaking space hi",
"Page break": "Page break hi",
"Paste as text": "Paste as text hi",
"Preview": "Preview hi",
"Print": "Print hi",
"Save": "Save hi",
"Find": "Find hi",
"Replace with": "Replace with hi",
"Replace": "Replace hi",
"Replace all": "Replace all hi",
"Prev": "Prev hi",
"Next": "Next hi",
"Find and replace": "Find and replace hi",
"Could not find the specified string.": "Could not find the specified string. hi",
"Match case": "Match case hi",
"Whole words": "Whole words hi",
"Spellcheck": "Spellcheck hi",
"Ignore": "Ignore hi",
"Ignore all": "Ignore all hi",
"Finish": "Finish hi",
"Add to Dictionary": "Add to Dictionary hi",
"Insert table": "Insert table hi",
"Table properties": "Table properties hi",
"Delete table": "Delete table hi",
"Cell": "Cell hi",
"Row": "Row hi",
"Column": "Column hi",
"Cell properties": "Cell properties hi",
"Merge cells": "Merge cells hi",
"Split cell": "Split cell hi",
"Insert row before": "Insert row before hi",
"Insert row after": "Insert row after hi",
"Delete row": "Delete row hi",
"Row properties": "Row properties hi",
"Cut row": "Cut row hi",
"Copy row": "Copy row hi",
"Paste row before": "Paste row before hi",
"Paste row after": "Paste row after hi",
"Insert column before": "Insert column before hi",
"Insert column after": "Insert column after hi",
"Delete column": "Delete column hi",
"Cols": "Cols hi",
"Rows": "Rows hi",
"Width": "Width hi",
"Height": "Height hi",
"Cell spacing": "Cell spacing hi",
"Cell padding": "Cell padding hi",
"Caption": "Caption hi",
"Left": "Left hi",
"Center": "Center hi",
"Right": "Right hi",
"Cell type": "Cell type hi",
"Scope": "Scope hi",
"Alignment": "Alignment hi",
"H Align": "H Align hi",
"V Align": "V Align hi",
"Top": "Top hi",
"Middle": "Middle hi",
"Bottom": "Bottom hi",
"Header cell": "Header cell hi",
"Row group": "Row group hi",
"Column group": "Column group hi",
"Row type": "Row type hi",
"Header": "Header hi",
"Body": "Body hi",
"Footer": "Footer hi",
"Border color": "Border color hi",
"Insert template": "Insert template hi",
"Templates": "Templates hi",
"Template": "Template hi",
"Text color": "Text color hi",
"Background color": "Background color hi",
"Custom...": "Custom... hi",
"Custom color": "Custom color hi",
"No color": "No color hi",
"Table of Contents": "Table of Contents hi",
"Show blocks": "Show blocks hi",
"Show invisible characters": "Show invisible characters hi",
"Words: {0}": "Words: {0} hi",
"{0} words": "{0} words hi",
"File": "File hi",
"Edit": "Edit hi",
"Insert": "Insert hi",
"View": "View hi",
"Format": "Format hi",
"Table": "Table hi",
"Tools": "Tools hi",
"Powered by {0}": "Powered by {0} hi",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help hi",
"Fonts": "Fonts hi",
});